### ISSUE TITLE
`[INFO] Maximum retries on media playlist reached, exiting...` with a turbo token

### ISSUE THREAD

**Issue by brian6932** [2bc4/twitch-hls-client#23]
Started with debug mode, no other error. Can't use debug patches as there's no longer a custom http patch, does just building it with `--debug` work?
Full logs https://i.alienpls.org/pUn

**Comment by 2bc4** [comment]
Is this reproducible or a one off stream hiccup? Seems fine on my end right now with a token.

**Comment by brian6932** [comment]
🤷 Not sure, I'll bump if I see it again

**Comment by brian6932** [comment]
Not sure if this is the same error, but I did build it as debug, so maybe that's why I'm getting this now instead
```
Worker error: request or response body error: error reading a body from connection: stream error received: unexpected internal error encountered
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
```

**Comment by 2bc4** [comment]
I've had that also and I have no idea. I think I'm going to revert this release and switch to curl, seems much more stable for this.
