### ISSUE TITLE
Error: Error parsing #EXT-X-MEDIA-SEQUENCE Caused by: invalid digit found in string

### ISSUE THREAD

**Issue by brian6932** [2bc4/twitch-hls-client#4]
Idk if this is a ttvlol issue, or a `twitch-hls-client` issue 🤷

**Comment by 2bc4** [comment]
>Idk if this is a ttvlol issue

No that's from parsing the playlist from Twitch servers. Was this a random one-off error or is it reproducible? If it's a one-off it could probably be fixed by trying again instead of exiting when parsing fails.

**Comment by brian6932** [comment]
it was a one-off as far as I can tell, but if I get it again, I'll make sure to mention
